apiVersion: v1
kind: Service
metadata:
  name: hello-k7s
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-k7s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k7s
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 4
  selector:
    matchLabels:
      app: hello-k7s
  template:
    metadata:
      labels:
        app: hello-k7s
    spec:
      containers:
        - name: hello-k7s
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

